### ISSUE TITLE
logic: generated seed not fully accessible (full entrance rando, keysanity, 100% locations)

### ISSUE THREAD

**Issue by foxsouns** [daid/LADXR#70]
These settings don't normally fail (I got a valid one right after this one), but I ran into this one. Hard logic, Insanity full entrance randomizer, Keysanity, with 100% locations on. Full settings string in the traceback. Didn't specify a seed, and it doesn't provide it upon an error: maybe this should be done in the future so that these issues are replicable?

```
Short settings string: LhhsHTWRDKruEIlc>,Cannot access:  [],Cannot access:  [],Cannot access:  [GoldLeaf:05a],Cannot access:  [GoldLeaf:058],Cannot access:  [],Cannot access:  [],Cannot access:  [Chest:018],Cannot access:  [],Cannot access:  [],Cannot access:  [],Cannot access:  [],Cannot access:  [KeyLocation],Cannot access:  [GoldLeaf:2d2],Cannot access:  [GoldLeaf:2c5],Cannot access:  [],Cannot access:  [TradeSequenceItem:019],Not all locations are accessible anymore with the full item pool
Traceback (most recent call last):
  File "/home/pyodide/main.py", line 133, in main
    r = randomizer.Randomizer(args, settings, seed=userSeed)
  File "/home/pyodide/randomizer.py", line 71, in __init__
    item_placer.run(self.rnd)
  File "/home/pyodide/randomizer.py", line 228, in run
    assert self.logicStillValid(), "Sanity check failed: %s" % (self.logicStillValid(verbose=True))
AssertionError: Sanity check failed: False
```

**Comment by foxsouns** [comment]
i dont think this is resolvable like this, without a seed.
